version: '1.0'
name: pipeline-20250113
displayName: docker_build
triggers:
  trigger: auto
stages:
  - name: stage-431c873c
    displayName: docker build
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: crpi-0lte4oc0s41r9qw7.cn-hangzhou.personal.cr.aliyuncs.com
        username: moonbite
        password: daohaokechi12345
        tag: dlmu-cone/one-store:v0.${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: true
        parameter: {}
        notify: []
        strategy:
          retry: '0'
